version: 2.1

orbs:
  move-ci: moverdc/move-ci@2.0.0
  slack: circleci/slack@5.1.1

workflow-anchors:
  any-branch-job: &any-branch-job
    filters:
      branches:
        ignore:
          - main
          - /^feature\/.*/
          - /^release\/.*/
          - ir.datascience.int
  feature-branch-job: &feature-branch-job
    filters:
      branches:
        only:
          - /^feature\/.*/
          - ir.datascience.int
  release-branch-job: &release-branch-job
    filters:
      branches:
        only: /^release\/.*/
  main-branch-job: &main-branch-job
    filters:
      branches:
        only: main
  slack-notifications:
    - &slack-if-job-failed
      slack/notify:
        event: fail
        channel: techmod-s4-test
        template: SLACK_TPL_RDP_FAILURE_DETAILED_LATEST
    - &slack-if-job-succeeded
      slack/notify:
        event: pass
        channel: techmod-s4-test
        template: SLACK_TPL_RDP_SUCCESS_DETAILED_LATEST
  notify-success-and-fail: &notify-success-and-fail
    post-steps:
      - *slack-if-job-succeeded
      - *slack-if-job-failed
  notify-fail: &notify-fail
    post-steps:
      - *slack-if-job-failed
  exclude-base-branch: &exclude-base-branch
    filters:
      branches:
        ignore:
          - main
  only-pr: &only-pr
    filters:
      branches:
        ignore:
          - main
          - /dev\/.*/
          - /feature\/.*/
          - /master/
          - ir.datascience.int
  aws-account: &aws-account
    type: enum
    enum: [AWS_ACCOUNT_SDSREAD_DEV, AWS_ACCOUNT_SDSREAD_QA, AWS_ACCOUNT_SDSREAD_PROD]
  aws-id: &aws-id
    type: string
  aws-ecr-repo-name: &aws-ecr-repo-name
    type: string
  short-env: &short-env
    type: string
    default: "dev"
executors:
  python-executor:
    docker:
      - image: cimg/python:3.12
  linux-vm:
    machine:
      image: ubuntu-2204:current
      docker_layer_caching: true

jobs:
  run-tests-and-sonar-scan:
    description: "Run unit tests on created docker image and run sonar scan"
    executor: linux-vm
    parameters:
      aws-id: *aws-id
    steps:
      - checkout
      - move-ci/aws-tunnel-up
      - move-ci/aws-proxy-up:
          export-proxy-variables: http
      - move-ci/aws-web-auth:
          role-arn: arn:aws:iam::<<parameters.aws-id>>:role/cicd-circleci-ecr-oidc-role
      - move-ci/ecr-login:
          region: us-west-2
          registry-id: <<parameters.aws-id>>
      - attach_workspace:
          at: /tmp
      - run: mkdir reports
      - run:
          name: Load CUSTOM_TAG from workspace
          command: |
            CUSTOM_TAG=$(cat /tmp/custom_tag)
            echo "export CUSTOM_TAG=${CUSTOM_TAG}" >> $BASH_ENV
      - run:
          command: |
            IMAGE=<<parameters.aws-id>>.dkr.ecr.us-west-2.amazonaws.com/sdsread/ir-data-science-integration:${CUSTOM_TAG}
            echo aws-id : <<parameters.aws-id>>
            echo ${CIRCLE_SHA1:0:8}
            echo $IMAGE
      #       docker pull $IMAGE
      #       echo "Running unit tests"
      #       docker run -it --user root $IMAGE bash -c "./run_tests.sh"
      #       CONTAINER_ID=$(docker ps -lq)
      #       echo "Copying coverage report from docker image for re-use in SonarQube line coverage check"
      #       docker cp $CONTAINER_ID:/app/coverage ./reports/coverage
      #       cp ./reports/coverage/coverage.xml ./reports/coverage.xml
      #       echo "Stopping and removing container"
      #       docker container stop $CONTAINER_ID
      #       docker container rm $CONTAINER_ID
      # - run:
      #     command: |
      #       echo "sonar.python.coverage.reportPaths=reports/coverage.xml" > sonar-project.properties
      # - move-ci/sonar-scan:
      #     extra-args: "-Dsonar.sources=ModelIntegration
      #                 -Dsonar.exclusions=**/tests/**,**/docker-compose/**
      #                 -Dsonar.python.coverage.reportPaths=reports/coverage.xml"

  push-image-ecr:
    description: "Build and push Docker image to ECR"
    executor: linux-vm
    steps:
      - checkout
      - move-ci/aws-tunnel-up
      - move-ci/aws-proxy-up:
          export-proxy-variables: http
      - attach_workspace:
          at: .
      - run:
          name: list files in workspace
          command: |
            echo "Listing files in workspace:"
            ls -la .
      - run:
          name: Set custom environment variable with date-time
          command: |
            TIMESTAMP=$(TZ=Asia/Kolkata date +"%m%d-%H%M")
            CUSTOM_TAG="${CIRCLE_SHA1}-${TIMESTAMP}"
            echo "export CUSTOM_TAG=${CUSTOM_TAG}" >> $BASH_ENV
            echo "${CUSTOM_TAG}" > /tmp/custom_tag
      - persist_to_workspace:
          root: /tmp
          paths:
            - custom_tag
      - move-ci/ecr-build-and-push:
          repository-name: sdsread/techmod-s4
          repository-tag-component: techmod-s4
          repository-tag-owner: techmod-s4 
          repository-tag-product: s4_backend  
          tags: ${CUSTOM_TAG}  # Include CUSTOM_TAG in tags
          # skip-when-tags-exist: true

  update-imagetag:
    description: "Update the tag"
    executor: linux-vm
    parameters:
      short-env:
        type: string
    steps:
      - attach_workspace:
          at: /tmp
      - run:
          name: Load saved CUSTOM_TAG
          command: |
            CUSTOM_TAG=$(cat /tmp/custom_tag)
            echo "export CUSTOM_TAG=${CUSTOM_TAG}" >> $BASH_ENV
      - move-ci/gh-install
      - run:
          name: Clone the repository manually
          command: |
            git clone https://${GH_PAT}@github.com/MoveRDC/techmod-s4.argo.git
            cd techmod-s4
            git checkout dev
            git pull origin dev

      - run:
          name: Update `values.dev.yaml`
          command: |
            cd ir.data.science.integration.argo
            if ! command -v yq &> /dev/null; then
              wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/local/bin/yq
              chmod +x /usr/local/bin/yq
            fi
            yq eval -i '.rollout.containers[0].image.tag = env(CUSTOM_TAG)' helm/values.dev.yaml

      - run:
          name: Commit & Push to `dev`
          command: |
            cd ir.data.science.integration.argo
            git config --global user.email "circleci-move@moveci.com"
            git config --global user.name "CircleCI Bot"
            git add helm/values.dev.yaml
            git commit -m "Auto-update image tag to $CUSTOM_TAG" || echo "No changes to commit."
            git push origin dev || echo "Push failed! Check permissions."

workflows:
  any-branch:
    jobs:  
      - push-image-ecr:
          name: push-image-ecr-any-branch
          context: [aws, slack-circleci-bot]  
          <<: *any-branch-job
          <<: *notify-fail
      
      - run-tests-and-sonar-scan:
          name: unit-test-and-sonarqube
          aws-id: "799269618777"
          requires:
            - push-image-ecr-any-branch
          context:
            - aws
            - sonarqube
            - github
            - slack-circleci-bot
          <<: *any-branch-job
          <<: *notify-fail
        
  feature-branch:
    jobs:
      - push-image-ecr:
          name: push-image-ecr-dev
          context: [aws, slack-circleci-bot]  
          <<: *feature-branch-job
          <<: *notify-fail
      
      - run-tests-and-sonar-scan:
          name: unit-test-and-sonarqube-dev
          aws-id: "799269618777"
          requires:
            - push-image-ecr-dev
          context:
            - aws
            - sonarqube
            - github
            - slack-circleci-bot
          <<: *feature-branch-job
          <<: *notify-fail

      # - update-imagetag:
      #     name: update-imagetag-dev
      #     short-env: dev
      #     context: [aws, github, slack-circleci-bot]
      #     <<: *feature-branch-job
      #     requires:
      #       - push-image-ecr-dev

  release-branch:
    jobs:
      - push-image-ecr:
          name: push-image-ecr-qa
          context: [aws, slack-circleci-bot]  
          <<: *release-branch-job
          <<: *notify-fail
      
      - run-tests-and-sonar-scan:
          name: unit-test-and-sonarqube-qa
          aws-id: "799269618777"
          requires:
            - push-image-ecr-qa
          context:
            - aws
            - sonarqube
            - github
            - slack-circleci-bot
          <<: *release-branch-job
          <<: *notify-success-and-fail

  main-workflow:
    jobs:
      - push-image-ecr:
          name: push-image-ecr-main
          context: [aws, slack-circleci-bot]  
          <<: *main-branch-job
          <<: *notify-fail

      - run-tests-and-sonar-scan:
          name: unit-test-and-sonarqube-main
          aws-id: "799269618777"
          requires:
            - push-image-ecr-main
          context:
            - aws
            - sonarqube
            - github
            - slack-circleci-bot
          <<: *main-branch-job
          <<: *notify-fail
